### ISSUE TITLE
使用项目目录下的dockerfile构建镜像无法启动容器

### ISSUE THREAD

**Issue by iefhong** [pengchujin/oneSubscribe#13]
docker build --tag ss-node-api:latest .
docker tag <image-id> ss-node-api

docker run --name ss-node-api -v /home/iefhong/ss-nodes/workdir-code/:/code -p 50100:3001 -d ss-node-api
启动即退出
 Stopped with exit code 0

docker run -it ss-node-api:latest /bin/bash
进入容器cmd，发现code 文件夹下只有package.json文件

**Comment by iefhong** [comment]
克隆项目到本地
修改Dockerfile 如下
```dockerfile
FROM node:10.24
MAINTAINER iefhong <iefhong.ssmgr@gmail.com>

WORKDIR /code

COPY . /code/

RUN yarn install --production

ENV NODE_ENV production
EXPOSE 3001
CMD ["node", "src/app.js"]
```
```bash
docker build --tag ss-node-api:latest .

docker run -it ss-node-api:latest /bin/bash
```

bash下输出
```bash
root@e0d68d6131e7:/code# yarn start
yarn run v1.22.5
$ ts-node src/app.ts
(node:279) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
(node:279) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:279) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 1.05s.


root@e0d68d6131e7:/code# node src/app.ts 
/code/src/app.ts:1
import * as Koa from 'koa'
       ^

SyntaxError: Unexpected token *
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

```
